### ISSUE TITLE
Respect folder layout of imported comp tracks.

### ISSUE THREAD

**Issue by philderbeast** [kuaka/airscore#47] opened 2020-02-20 07:15 UTC
If we're importing comps from `*.fsdb` then can we opt to respect the folder layout of the tracks. Here's an example for Dalby 2017:

```
> pwd
/.../airscore/airscore/data/tracks/2017/dalby
> tree . --charset -d -L 1
.
|-- day\ five
|-- day\ four
|-- day\ one
|-- day\ seven
`-- day\ six

5 directories, 0 files
```

This would enable us to copy as-is the tracks when scoring with FS and scoring with airscore.

**Comment by philderbeast** [comment] 2020-02-20 07:18
As it stands I have to rename these folders to:

```
> pwd
/.../airscore/airscore/data/tracks/2017/dalby
> tree . --charset -d -L 1
.
|-- t1_20170409
|-- t2_20170412
|-- t3_20170413
|-- t4_20170414
`-- t5_20170415

5 directories, 0 files
```

**Comment by kuaka** [comment] 2020-02-20 07:41
this is very do-able as the paths are stored in the DB. So instead of generating the paths then storing in the DB we can read from somewhere and store.. the question is where do we get the folder structure for the files? I guess it is not in FSDB or is it?

**Comment by philderbeast** [comment] 2020-02-20 07:52
The paths are in the `*.fsdb` and may be deep.

```xml
# dalby 2017
<FsTask id="1" name="day one" tracklog_folder="day one">

# forbes 2017
<FsTask id="1" name="Well we'll think about it..." tracklog_folder="scoring\day 1">
```

**Comment by kuaka** [comment] 2020-02-20 08:20
I'll assign to Antonio as he wrote the FSDB part

**Comment by biuti** [comment] 2020-02-23 12:42
> The paths are in the `*.fsdb` and may be deep.
> 
> ```
> # dalby 2017
> <FsTask id="1" name="day one" tracklog_folder="day one">
> 
> # forbes 2017
> <FsTask id="1" name="Well we'll think about it..." tracklog_folder="scoring\day 1">
> ```

In new_missing_distance branch I committed a new script, import_fsdb.py, that is quite easy to use.
I merged with flask earlier today so Stuart will probably merge in Flask in the next days so we can delete this branch and others.
By now, it assumes usdb file is in core folder, but it accept absolute path.

`python import_fsdb.py 'fsdb_name.fsdb' 'comp_short_name' keep_folder_names_bool from_CIVL_bool`

where:

- fsdb_name.fsdb STR is the fsdb filename
- comp_short_name STR is comp.comp_code. if 0 will be calculated from comp_name
- keep_folder_names 0/1 if 1 will read folder names from fsdb, otherwise will create from task_num and date
- from_CIVL 0/1 if 1 will try to get pilots name, nat, sex from CIVL database, given we have CIVLID

At the end of the process, you get comp_id, and comp folder.
tasks tracks folders should be created as well, with correct naming depending on choose option.
It should work as intended. Please test and let me know.

**Comment by kuaka** [comment] 2020-03-16 21:05
can this be closed now?

**Closed** 2020-03-16 22:02 UTC
